#include <gtest/gtest.h>

#include "arch/x86_64/patcher.h"
#include "os/memory.h"

#include <array>
#include <algorithm>
#include <cstdint>
#include <cstring>

namespace {
// This binary never executes the generated bytes. The OS seam lets the real
// patcher prepare and relocate a trampoline, then denies permission to publish.
alignas(16) std::array<std::uint8_t, 256> trampoline_storage{};
unsigned allocations = 0;
unsigned frees = 0;
unsigned writable_requests = 0;
unsigned restore_requests = 0;
bool allow_write = false;
std::size_t writable_size = 0;
std::size_t restored_size = 0;
void* writable_address = nullptr;
void* restored_address = nullptr;
}

namespace splice::os {
void* allocate_executable_memory(std::size_t size, const void*) {
    EXPECT_LE(size, trampoline_storage.size());
    ++allocations;
    return trampoline_storage.data();
}
void free_executable_memory(void* memory, std::size_t) {
    EXPECT_EQ(memory, trampoline_storage.data());
    ++frees;
}
bool make_executable_writable(void* address, std::size_t size) {
    ++writable_requests;
    writable_size = size;
    writable_address = address;
    return allow_write;
}
void restore_executable(void* address, std::size_t size) {
    ++restore_requests;
    restored_address = address;
    restored_size = size;
}
void flush_instruction_cache(void*, std::size_t) {}
std::size_t page_size() { return 4096; }
}

// T-011-13: failure must not publish a trampoline that cleanup releases.
TEST(PatcherFailure, denied_write_does_not_publish_or_modify_target) {
    alignas(16) std::array<std::uint8_t, 64> target{};
    target.fill(0x90);  // Relocatable NOPs, no accidental earlier decode failure.
    const auto before = target;
    int sentinel = 0;
    void* original = &sentinel;
    unsigned callback_calls = 0;
    allocations = frees = writable_requests = restore_requests = 0;
    allow_write = false;

    const auto result = splice::arch::x86_64::install_inline_patch(
        target.data(), target.data() + 32, &original,
        [](void*, void* user) { ++*static_cast<unsigned*>(user); }, &callback_calls);

    EXPECT_EQ(result, nullptr);
    EXPECT_EQ(writable_requests, 1u);  // Prove the intended failure was reached.
    EXPECT_EQ(allocations, 1u);
    EXPECT_EQ(frees, 1u);
    EXPECT_EQ(restore_requests, 0u);
    EXPECT_EQ(callback_calls, 0u);
    EXPECT_EQ(original, &sentinel);
    EXPECT_EQ(target, before);
}

// T-011-16: fixture distances are checked, not assumed across all toolchains.
// The synthetic replacement is deliberately a terabyte away.
TEST(PatcherFailure, strict_range_and_permission_matrix) {
    alignas(16) static std::array<std::uint8_t, 64> near_target{};
    alignas(16) std::array<std::uint8_t, 64> far_target{};
    const auto distance = reinterpret_cast<std::uintptr_t>(far_target.data()) >
                      reinterpret_cast<std::uintptr_t>(trampoline_storage.data())
                  ? reinterpret_cast<std::uintptr_t>(far_target.data()) -
                        reinterpret_cast<std::uintptr_t>(trampoline_storage.data())
                  : reinterpret_cast<std::uintptr_t>(trampoline_storage.data()) -
                        reinterpret_cast<std::uintptr_t>(far_target.data());
    if (distance <= 0x80000000ull) {
        GTEST_SKIP() << "This OS/toolchain did not place the stack fixture beyond rel32";
    }
    for (unsigned scenario = 0; scenario != 4; ++scenario) {
        auto& target = scenario == 1 || scenario == 3 ? near_target : far_target;
        target.fill(0x90);
        if (scenario == 2) {
            // RIP-relative load cannot relocate from stack to the far block.
            const unsigned char rip[] = {0x8b, 0x05, 0, 0, 0, 0};
            std::copy(std::begin(rip), std::end(rip), target.begin());
        }
        const auto expected = target;
        void* destination = scenario == 2 ? target.data() + 32 :
            reinterpret_cast<void*>(reinterpret_cast<std::uintptr_t>(target.data()) +
                                    (1ull << 40));
        unsigned calls = 0;
        void* original = nullptr;
        allocations = frees = writable_requests = restore_requests = 0;
        allow_write = scenario != 3;
        const auto result = splice::arch::x86_64::install_inline_patch(
            target.data(), destination, &original,
            [](void*, void* user) { ++*static_cast<unsigned*>(user); }, &calls,
            nullptr, nullptr, expected.data());
        if (scenario == 1) {
            EXPECT_EQ(result, target.data());
            EXPECT_EQ(original, trampoline_storage.data());
            EXPECT_EQ(calls, 1u);
            EXPECT_EQ(target[0], 0xe9);
            std::int32_t displacement = 0;
            std::memcpy(&displacement, target.data() + 1, sizeof(displacement));
            EXPECT_EQ(reinterpret_cast<std::intptr_t>(target.data()) + 5 + displacement,
                      reinterpret_cast<std::intptr_t>(trampoline_storage.data() + 128));
            EXPECT_EQ(writable_requests, 1u);
            EXPECT_EQ(restore_requests, 1u);
            EXPECT_EQ(writable_address, restored_address);
            EXPECT_EQ(writable_size, 5u);
            EXPECT_EQ(restored_size, writable_size);
            EXPECT_EQ(frees, 0u);
            EXPECT_TRUE(std::equal(target.begin() + 5, target.end(), expected.begin() + 5));
        } else {
            EXPECT_EQ(result, nullptr);
            EXPECT_EQ(calls, 0u);
            EXPECT_EQ(original, nullptr);
            EXPECT_EQ(target, expected);
            EXPECT_EQ(frees, 1u);
            EXPECT_EQ(writable_requests, scenario == 3 ? 1u : 0u);
            EXPECT_EQ(restore_requests, 0u);
        }
    }
}
